name: Mini Todo App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    name: Run Backend API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: npm install
        working-directory: ./server

      - name: Run backend tests
        run: npm test -- --coverage
        working-directory: ./server

      - name: Upload backend coverage report
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage-report
          path: ./server/coverage

  frontend-tests:
    name: Run Frontend UI Tests
    runs-on: ubuntu-latest
    needs: backend-tests   

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies (needed to start backend server)
        run: npm install
        working-directory: ./server

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./client

      - name: Start backend server
        run: |
          nohup node ./server/index.js &
          sleep 5  # wait for server to start

      - name: Start frontend dev server
        run: |
          nohup npm run dev --prefix ./client &
          sleep 10  # wait for frontend to start

      - name: Run Cypress tests
        run: npm run cypress:run
        working-directory: ./client
